### ISSUE TITLE
iframe transparency when website sets color-scheme dark

### ISSUE THREAD

**Issue by davidscotson** [jrolfs/gruvbox-material-tridactyl#2]
Hi, nice theme, thank you.

I noticed an oddity on github.com when using their dark mode styles, I filed it upstream with tridactyl as I noticed it affects one of the core themes too, but it was more noticeable with this theme due to more use of transparency. There's more details here https://github.com/tridactyl/tridactyl/issues/4294

**Comment by davidscotson** [comment]
![Screenshot 2022-06-30 at 21 56 30](https://user-images.githubusercontent.com/7288187/176778812-bcfb76d9-a187-4fea-af7e-5712d2d8cbe0.png)

**Comment by jrolfs** [comment]
Thanks for filing an issue! I'll look into this as soon as I can. Could you supply the OS / browser version when you get a chance? I'm curious why this doesn't seem to affect me.

**Comment by davidscotson** [comment]
Version details when I see this are:

Mac OS 12.3.1 (21E258)
Firefox 102.0 (64-bit)
Tridactyl 1.22.1

**Comment by jrolfs** [comment]
Thanks for the details. Interestingly I was unable to reproduce this until I upgrade Firefox. I should have noted which version I was on... it was either 100 or 101, because it makes this kinda feel like a regression on Firefox's side? Thanks for the details in https://github.com/tridactyl/tridactyl/issues/4294. In my futzing, it seems like if I set the `color-scheme` from _within_ the `iframe` document to the same `color-scheme` as the parent document, it fixes things (which makes sense). The problem is, without some mechanism for communicating that to the Tridactyl frame, we run into problems keeping those in sync.

Weirdly, as you stated in the other issue, setting `color-scheme: light` on the `iframe` element from the parent frame seems to resolve the issue without having to worry about syncing? Super weird, but I don't really have time to mess around with this right now so I think I'm just gonna make that change and see what happens down the line. I think Tridactyl probably already has some mechanism for handling this more reliably (like syncing the parent color scheme) so I'll keep an eye on the other ticket in the meantime.

**Comment by jrolfs** [comment]
When you get a chance can you let me know if https://github.com/jrolfs/gruvbox-material-tridactyl/releases/tag/v0.1.1 resolves the issue for you for now @davidscotson?

```sh
:colourscheme --url https://github.com/jrolfs/gruvbox-material-tridactyl/releases/download/v0.1.1/dark-soft.css gruvbox-material-dark-soft
```

**Comment by davidscotson** [comment]
Yes that works for me.

I initially didn't think it was working, but tried it in a fresh install and it worked, and then it appeared to work with my usual browser after I'd restarted the browser itself.
